name: Build Blog
on: push
permissions:
  contents: write
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --all-extras
      - name: Creating HTML from Markdown
        run: |
          poetry run python build.py
      - name: Publish HTML blog
        run: |
          git config --global user.name 'Amaan Khan'
          git config --global user.email '71920621+amaank404@users.noreply.github.com'
          git add blog
          git commit -am "Automated blog html publish"
          git push
